/*
 * Lab5.c (Part 2)
 *
 * Created: 5/24/2017 2:27:49 PM
 * Author : Oscar Choy
 *
 * This project uses an ATMega328P board, a potentiometer, and a piezoelectric buzzer to
 * project a sound of variable frequency, according to the position of the knob on the 
 * potentiometer. Using Analog-to-Digital conversion, the degree the knob of the potentiometer
 * is turned to will be converted into a value that will determine the frequency of the sound
 * generated by the buzzer.
 */

#define F_CPU 16000000UL
#define TIMER0_CNT 150

#include <avr/io.h>
#include <util/delay.h>
#include <avr/interrupt.h>
#include <stdlib.h>
#include <stdbool.h>

void InitTimer0(void);
void ADC_Init();
unsigned char GetADCResult(void);

float tempVal = 0.0;
int currVal = 0;
int main(void)
{
	DDRC |= 1<<DDB0;
	DDRC |= 0<<DDB1;
	PORTC |= 1<<PORTC0;
	PORTC |= 1<<PORTC1;
	
	InitTimer0();
	ADC_Init();
	sei();
	
	while(1) {
		tempVal = 8.0 + (GetADCResult() * (8.0/255));
		OCR0A = (char)tempVal;
	}
	
	return 0;
}

void InitTimer0(void) {
	TCCR0A = 0b00000000;
	TCCR0B = 0b00000101;
	OCR0A = TIMER0_CNT;
	TIMSK0 = _BV(OCIE0A);
	TCNT0 = 0;
}

ISR(TIMER0_COMPA_vect) {
	PORTC ^= (1<<PORTC0);
	TCNT0 = 0;
}

void ADC_Init() {
	ADMUX |= (1<<REFS0) | (1<<MUX0) | (1<<ADLAR); 
	ADCSRA |= (1<<ADEN) | (1<<ADPS2) | (1<<ADPS1) | (1<<ADPS0);
}

unsigned char GetADCResult(void) {
	ADCSRA |= (1<<ADSC);
	while (ADCSRA & 1<<ADSC);
	return(ADCH);
}